name: "Create Card"
description: "Create a LeanKit card"
inputs:
  api-token:
    description: Api token with write access to your LeanKit board
    required: true
  leankit-board-url:
    description: Url of the board where cards should be created
    required: true
  type-id:
    description: Optionally specify a card type id to use
    required: false
  review-lane:
    description: Id or title of your "ready to review" lane
    required: true
  ready-to-merge-lane:
    description: Id or title of your "ready-to-merge" lane
    required: true
outputs:
  result:
    description: Object with result message or createdCardId
runs:
  using: "node12"
  main: "dist/index.js"