name: testDependabot
on:
  pull_request:
      branches: [ master ]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create card in leankit
        uses: ./actions/createCardFromDependabotPR
        with:
          api-token: ${{ secrets.D03_DEPENDABOT_API_TOKEN }}
          leankit-board-url: https://d03.leankit.io/board/10126868525
          review-lane: 10126868626
          ready-to-merge-lane: 10126868629
          type-id: 10126868528
        id: create
      - name: Output results
        run: echo "Done- ${{ steps.create.outputs.result }}"

